trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  configuration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.101'
  displayName: 'Install .Net Core 2.2 SDK' # Needed for test filtering
- script: |
    dotnet tool install --tool-path . nbgv
    .\nbgv cloud
  displayName: 'Install NerdBank.GitVersioning'
- script: |
    dotnet build --configuration $(configuration)
  displayName: 'Build Release'
- script: |
    dotnet test --configuration $(configuration) --logger trx --collect "Code coverage"
  displayName: 'Run tests'
- script: |
    dotnet publish src/Cle.Frontend --configuration $(configuration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Package Cle.Frontend'
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publish test results'
