trigger:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - docs/*

pool:
  vmImage: 'windows-2019'

variables:
  configuration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.203'
  displayName: 'Install .NET Core SDK that supports C# 8.0'
- script: |
    dotnet tool install --tool-path . nbgv
    .\nbgv cloud
  displayName: 'Install NerdBank.GitVersioning'
- script: |
    dotnet tool install --tool-path . dotnet-sonarscanner
    .\dotnet-sonarscanner begin /k:"polsys_cle" /v:"$(Build.BuildNumber)" /o:"polsys-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(SONAR_TOKEN)" /d:sonar.pullrequest.key=$(System.PullRequest.PullRequestNumber) /d:sonar.pullrequest.branch="$(Build.SourceBranch)" /d:sonar.pullrequest.base="$(System.PullRequest.TargetBranch)"
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Install SonarScanner (PR)'
- script: |
    dotnet tool install --tool-path . dotnet-sonarscanner
    .\dotnet-sonarscanner begin /k:"polsys_cle" /v:"$(Build.BuildNumber)" /o:"polsys-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(SONAR_TOKEN)"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Install SonarScanner (CI)'
- script: |
    dotnet build --configuration $(configuration)
  displayName: 'Build Release'
- script: |
    dotnet test --configuration $(configuration) --no-build --logger trx --collect "Code Coverage" --filter "FullyQualifiedName~UnitTests"
  displayName: 'Run unit tests'
- script: |
    dotnet test --configuration Release --no-build --logger trx test/Cle.IntegrationTests/Cle.IntegrationTests.csproj
  displayName: 'Run integration tests' # Code coverage hangs/crashes the Cle-compiled executables
- script: |
    dotnet publish src/Cle.Frontend --configuration $(configuration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Package Cle.Frontend'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/cle-$(Build.BuildNumber).zip'
  displayName: 'Create .zip file'
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publish test results'
- script: |
    .\dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"
  condition: succeededOrFailed()
  displayName: 'Publish SonarScanner results'
