trigger:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - docs/*

pool:
  vmImage: 'windows-2019'

variables:
  configuration: 'Release'

steps:
- script: |
    dotnet tool install --tool-path . nbgv
    .\nbgv cloud
  displayName: 'Install NerdBank.GitVersioning'
- script: |
    dotnet build --configuration $(configuration)
  displayName: 'Build Release'
- script: |
    dotnet test --configuration $(configuration) --logger trx --collect "Code Coverage" --filter "FullyQualifiedName~UnitTests"
  displayName: 'Run unit tests'
- script: |
    dotnet test --configuration Release --logger trx test/Cle.IntegrationTests/Cle.IntegrationTests.csproj
  displayName: 'Run integration tests' # Code coverage hangs/crashes the Cle-compiled executables
- script: |
    dotnet publish src/Cle.Frontend --configuration $(configuration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Package Cle.Frontend'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    archiveFile: '$(Build.ArtifactStagingDirectory)/cle-$(Build.BuildId).zip'
  displayName: 'Create .zip file'
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publish test results'
