trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  configuration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.101'
  displayName: 'Install .Net Core 2.2 SDK' # Needed for test filtering
- script: |
    dotnet build --configuration $(configuration)
  displayName: 'Build Release'
- script: |
    dotnet test --configuration $(configuration)
  displayName: 'Run tests'
